// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.stgo.taostyle.domain.orders;

import com.stgo.taostyle.domain.orders.ShipmentStyle;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect ShipmentStyle_Roo_Configurable {
    
    declare @type: ShipmentStyle: @Configurable;
    
}
