// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.stgo.taostyle.domain.orders;

import com.stgo.taostyle.domain.orders.TaxonomyMaterialOrder;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect TaxonomyMaterialOrder_Roo_Configurable {
    
    declare @type: TaxonomyMaterialOrder: @Configurable;
    
}
