// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.stgo.taostyle.domain;

import com.stgo.taostyle.domain.MediaUpload;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect MediaUpload_Roo_Configurable {
    
    declare @type: MediaUpload: @Configurable;
    
}
